default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV["MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: soat_development
  host: localhost

test:
  <<: *default
  database: soat_test

# Heroku
production:
  <<: *default
  database: soat_production
  host: <%= ENV['DATABASE_URL'] %>
